// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ATTApp.Data.Sqllite.Models;

public partial class Number
{
    public int Id { get; set; }

    public int Value { get; set; }

    public int IsPrime { get; set; }
}