// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using ATTApp.Data.Models.Configurations;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
#nullable disable

namespace ATTApp.Data.Models;

public partial class attContext : DbContext
{
    public attContext(DbContextOptions<attContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Number> Numbers { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.ApplyConfiguration(new Configurations.NumberConfiguration());

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
