// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ATTApp.Data.Models;

[Table("Number")]
public partial class Number
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    public int Value { get; set; }

    public bool IsPrime { get; set; }
}