// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using ATTApp.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace ATTApp.Data.Models.Configurations
{
    public partial class NumberConfiguration : IEntityTypeConfiguration<Number>
    {
        public void Configure(EntityTypeBuilder<Number> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__Number__3214EC277914B9E1");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Number> entity);
    }
}
