// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using ATTApp.Data.Sqllite.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace ATTApp.Data.Sqllite.Models.Configurations
{
    public partial class NumberConfiguration : IEntityTypeConfiguration<Number>
    {
        public void Configure(EntityTypeBuilder<Number> entity)
        {
            entity.ToTable("Number");

            entity.Property(e => e.Id).HasColumnName("id");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Number> entity);
    }
}
